service: users

provider:
  name: aws
  runtime: nodejs6.10
  stage: ${opt:stage, self:custom.defaultStage}
  region: us-east-1
  memorySize: 128
  timeout: 15
  deploymentBucket: sls-depl-${self:provider.region}-${self:provider.stage}

resources:
  Resources:
    UsersTable:
      Type: "AWS::DynamoDB::Table"
      Properties:
        TableName: ${self:custom.userTableName}
        AttributeDefinitions:
          - AttributeName: "id"
            AttributeType: "S"
        KeySchema:
          - AttributeName: "id"
            KeyType: "HASH"
        ProvisionedThroughput:
          ReadCapacityUnits: "1"
          WriteCapacityUnits: "1"

custom:
  defaultStage: dev
  profiles:
    dev: development
    prod: production
  common: ${file(../config/common.json)}
  userTableName: ${self:custom.common.userTable}
